/*
  Auto-generated by Spline
*/

import type {MetaFunction} from '@shopify/remix-oxygen';
import useSpline from '@splinetool/r3f-spline';
import {OrthographicCamera} from '@react-three/drei';
import {Canvas} from '@react-three/fiber';
import {Suspense} from 'react';

export const meta: MetaFunction = () => {
  return [{title: 'Spline Test'}];
};

function Scene({...props}) {
  const {nodes, materials} = useSpline(
    'https://prod.spline.design/OKk8yaNkYucJ0USM/scene.splinecode',
  );
  return (
    <>
      <color attach="background" args={['#a8aec2']} />
      <group {...props} dispose={null}>
        <scene name="Scene 1">
          <directionalLight
            name="Directional Light"
            castShadow
            intensity={0.7}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={-10000}
            shadow-camera-far={100000}
            shadow-camera-left={-1000}
            shadow-camera-right={1000}
            shadow-camera-top={1000}
            shadow-camera-bottom={-1000}
            position={[200, 300, 300]}
          />
          <mesh
            name="Rectangle"
            geometry={nodes.Rectangle.geometry}
            material={materials['Rectangle Material']}
            castShadow
            receiveShadow
          />
          <OrthographicCamera
            name="1"
            makeDefault={true}
            far={10000}
            near={-50000}
          />
          <hemisphereLight
            name="Default Ambient Light"
            intensity={0.75}
            color="#eaeaea"
          />
        </scene>
      </group>
    </>
  );
}

export default function SplineTest() {
  return (
    <div style={{width: '100%', height: '100vh'}}>
      <Canvas shadows>
        <Suspense fallback={null}>
          <Scene />
        </Suspense>
      </Canvas>
    </div>
  );
}
